
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 31 08:44:59 GMT-03:00 2015
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 29;
  public static final int LT = 26;
  public static final int ELSE = 20;
  public static final int EXP2 = 7;
  public static final int INT = 24;
  public static final int EXP1 = 6;
  public static final int WHILE = 21;
  public static final int PCOMMA = 8;
  public static final int SUMA = 2;
  public static final int RETURN = 23;
  public static final int POINT = 9;
  public static final int IF = 18;
  public static final int LLI = 15;
  public static final int ASIGN = 10;
  public static final int GT = 28;
  public static final int ID = 33;
  public static final int empty = 25;
  public static final int NUM = 32;
  public static final int LLD = 16;
  public static final int PCI = 13;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int PRI = 11;
  public static final int PCD = 14;
  public static final int DIV = 5;
  public static final int PRD = 12;
  public static final int error = 1;
  public static final int EQ = 30;
  public static final int LEQ = 27;
  public static final int FOR = 22;
  public static final int NEQ = 31;
  public static final int VOID = 19;
  public static final int RESTA = 3;
}

