
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 21 18:20:41 GMT-03:00 2015
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 27;
  public static final int LT = 24;
  public static final int ELSE = 19;
  public static final int EXP2 = 7;
  public static final int INT = 23;
  public static final int EXP1 = 6;
  public static final int WHILE = 20;
  public static final int PCOMMA = 8;
  public static final int SUMA = 2;
  public static final int RETURN = 22;
  public static final int IF = 17;
  public static final int LLI = 14;
  public static final int ASIGN = 9;
  public static final int GT = 26;
  public static final int ID = 31;
  public static final int NUM = 30;
  public static final int LLD = 15;
  public static final int PCI = 12;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int PRI = 10;
  public static final int PCD = 13;
  public static final int DIV = 5;
  public static final int PRD = 11;
  public static final int error = 1;
  public static final int EQ = 28;
  public static final int LEQ = 25;
  public static final int FOR = 21;
  public static final int NEQ = 29;
  public static final int VOID = 18;
  public static final int RESTA = 3;
}

